# action.yml
name: 'CF-Helm-Push'
description: 'This action pushes a local chart to a CodeFresh hosted chart museum repository using a token'
branding:
  color: 'green'
  icon: 'upload-cloud'
outputs:
  time: # id of output
    description: 'The time it completed'
runs:
  using: 'docker'
  image: 'bsord/cf-helm-push'
