name: Build

on:
  push:
    branches:
      - master
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  IMAGE_NAME: bsord/helm-push
  PLATFORMS: linux/amd64

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Generate changelog and tag with new version
        id: get-next-version
        uses: bsord/conventional-changelog-action@v3.7.0
        with:
          github-token: ${{ secrets.github_token }}
          tag-prefix: 'v'
          skip-version-file: true
          fallback-version: 'v3'

      - name: Create Release
        if: ${{ steps.get-next-version.outputs.skipped == 'false' }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.get-next-version.outputs.version }}
          release_name: ${{ steps.get-next-version.outputs.version }}
          body: ${{ steps.get-next-version.outputs.clean_changelog }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          tags: ${{ env.IMAGE_NAME }}:${{ steps.get-next-version.outputs.version }}
          file: Dockerfile
          platforms: ${{ env.PLATFORMS }}
          push: true
